version: "3"

services:
  webserver:
     image: w1sh3r/lamp:7.2
     container_name: wplamp-php72
     restart: 'always'
     tty: true
     ports:
        - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
        - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
     volumes:
        - ${DOCUMENT_ROOT-./www}:/var/www/html
        - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
        - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
        - ${APACHE_LOG_DIR-./logs/apache2}:/var/log/apache2
     links:
        - database

  database:
     image: mysql:5.7
     container_name: wpdb
     restart: 'always'
     environment:
         MYSQL_ROOT_PASSWORD: strongpass1234
         MYSQL_DATABASE: app_db
         MYSQL_USER: devuser
         MYSQL_PASSWORD: pass1234
     ports:
        - "0.0.0.0:${HOST_MACHINE_MYSQL_PORT}:3306"
     volumes:
        - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
        - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
